### PR TITLE
Project cleanup

### PR DESCRIPTION
**Pull request by josefdolezal**
Hey @syky27, as mentioned in #11, I did some cleanup at the project:

- [x] Remove dependencies source from repository - #12 
- [x] Remove unnecessary dependencies - #11 
  - ~I did not remove SwiftyJSON library for now, since the Swift 4 JSON handling is not very convenient in this case~
- [x] Refactor the network layer to be less complicated
- [x] Refactor model objects to into separate files, use multiple menus for one restaurant (simulates food categories)
- [x] Remove unused files and test targets 
- [x] Map Xcode project to match 1:1 file system folder structure (default for Xcode 9)
- [x] Move parsing logic out of APIWrapper
- [x] Fix commit messages to match repo style
- [x] Basic error handling

~Since not everything is done, marked the PR as WIP.~ Feel free to add comments and/or proposals.
When this PR is merged, issues #8, #11 and #12 may be closed.

### CODE REVIEW

**Review by josefdolezal — COMMENTED** [review]
Uh, totally forget about this!

**Comment by syky27** [comment]
I would not fix this: `Fix commit messages to match repo style` for now...

**Comment by syky27** [comment]
CI tries to run this: `Installing Pods with 'bundle exec pod install'` 

That is nonsense, no idea where its coming from...

**Comment by syky27** [comment]
👌 VIP

**Comment by josefdolezal** [comment]
Hey @syky27, I removed the SwiftJSON after all - it was not easy, but not that hard as I thought. I also added back the headers for meal categories..

**Comment by syky27** [comment]
I believe this should be build passing commit, when it passes, I will squash my `CI:`  commits.

And I would like to to ask you to refactor commit messages to match repo style, when I am done.

Thanks @josefdolezal

**Comment by josefdolezal** [comment]
Hey @syky27, I rebased the commits - all todos are now done! Once the CI succeeds, it should be ready for merge.

**Pull request merged**
