### PR TITLE
Adds strings localization

### PR DESCRIPTION
**Pull request by josefdolezal**
This PR introduces CZ/EN localization discussed in #22. All hardcoded strings are now replaced with localized strings based on user's phone preferences.

Localization string keys are converted to name-spaced enum to ensure compile-time check of strings validity. The enums are generated with SwiftGen using aggregated Xcode target.

I have also added Danger action, which checks whether both languages are updated together. 

✅ The README is updated.

### CODE REVIEW

**Comment by syky27** [comment]
Why did those images got replaced?

**Comment by josefdolezal** [comment]
Uh, I forgot to mention it! I move all app Resources (assets catalog, splash screen story board and configuration plist) into Resources group - It makes the project structure cleaner.

It also looks like Travis is failing again for some reason.. o.O

**Comment by syky27** [comment]
No idea, why travis is failing those build logs are sometimes hell...

**Comment by josefdolezal** [comment]
This is really weird, it works just fine on my laptop..

**Comment by josefdolezal** [comment]
Cool, it works with new Xcode, I will squash the CI commits and it's ready to merge.

**Pull request merged**
