### PR TITLE
FIX: Modify both the SVG and the script to actually work

### PR DESCRIPTION
**Pull request by hroncok**

### CODE REVIEW

**Comment by syky27** [comment]
I think that I will use something like this tho...

```
convert -density 1200 -resize 40x40 icon.svg "../LunchGuy/Assets.xcassets/AppIcon.appiconset/Icon-40.png"
```

I just read how `qlmanage` is bad for this kind of stuff...

**Comment by hroncok** [comment]
Great, but keeping it in a function like presented here makes it easier to manage

**Comment by hroncok** [comment]
ImageMagick also doesn't respect the background.

**Comment by syky27** [comment]
@hroncok bash specialist, is this correct? 5f9fcb6af9e14c8fa06798d9d62a191313100dc7

**Comment by hroncok** [comment]
Works on Linux. Testing on Mac, installing ImageMagick.

**Comment by hroncok** [comment]
Ready from my POV.

**Pull request merged**
